config/routes.rb
Rails.application.routes.draw do

  root 'index#home'
  get 'services', to: 'index#services'
  get 'about', to: 'index#about'
  get 'contact', to: 'index#contact'
  get 'portfolio', to: 'index#projects'
  get 'portfolio/project_backyard', to: 'projects#project_backyard', as: 'project_backyard'

  get 'messages/new'
  get 'messages/create'

  post 'contact', to: 'messages#create'

  #Error routes
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Invalid routes
  get '*unmatched_route', to: 'errors#file_not_found'

  # Message Mailer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def file_not_found
  end

  def internal_server
  end

  def unprocessable
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  	@message = Message.new
  end

  def services
  end

  def about
  end

  def contact
  	@message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.valid?
        MessageMailer.new_message(@message).deliver
        format.js   { render :layout => false }
      else
        format.js   { render :layout => false }
      end
    end
  end

private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def project_backyard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/index/about.html.erb
<div class="view-head">
  <h2 class="animation" data-animation="animated fadeInRight">About Us</h2>
</div>
<div class="about-wrapper">
	<div class="container">
    <div class="page-head-right">
      <div class="head-info">
        <h1 class="animation" data-animation="animated fadeInLeft">Who we are</h1>
        <h6 class="animation" data-animation="animated fadeInLeft">BackyardLinks</h6>
      </div>
    </div>
  </div>
	<div class="light-wrapper">
	  <div class="light-information-wrapper col-lg-6">
	    <div class="light-information animation" data-animation="animated fadeInLeft">
	      <div class="page-head">
	        <h6>WE MAKE IT</h6>
	        <h1>Unlimited Creative</h1>
	        <p>This was one trait that advertising agencies were perceived to not always have. It was suggested that on occasions that media planner and researchers.</p>
	      </div>
	    </div>
	  </div>
	  <div class="light-window col-lg-6 animation" data-animation="animated fadeInRight">
	  	<%= image_tag 'about.jpg' %>
	  </div>
	</div>
	<div class="light-line col-lg-6 animation2" data-animation="animated fadeInLeft">
	  <div class="col-lg-6 light-image-wrapper">
	  	<div class="light-overlay"></div>
	    <%= image_tag 'mision.jpg' %>
	  </div>
	  <div class="light-content-wrapper col-lg-6 light-right">
	    <div class="light-content">
	      <span><i class="fas fa-rocket"></i></span>
	      <h3>Mission</h3>
	      <p>This was one trait that advertising agencies were perceived to not always have.</p>
	    </div>
	  </div>
	</div>
	<div class="light-line col-lg-6 animation2" data-animation="animated fadeInRight">
		<div class="col-lg-6 light-image-wrapper">
			<div class="light-overlay"></div>
	    <%= image_tag 'vision.jpg' %>
	  </div>
	  <div class="light-content-wrapper col-lg-6 light-right">
	    <div class="light-content">
	      <span><i class="far fa-lightbulb"></i></span>
	      <h3>Vision</h3>
	      <p>This was one trait that advertising agencies were perceived to not always have.</p>
	    </div>
	  </div>
	</div>
</div>

app/views/index/contact.html.erb
<div class="view-head">
  <h2 class="animation" data-animation="animated fadeInRight">Contact</h2>
</div>
<div class="contact-wrapper">
  <div class="container">
    <div class="page-head-right">
      <div class="head-info">
        <h1 class="animation" data-animation="animated fadeInLeft">Our Contacts</h1>
        <h6 class="animation" data-animation="animated fadeInLeft">How to contact us</h6>
      </div>
    </div>
  </div>
  <div style='width: 100%;' class="animation" data-animation="animated fadeInUp">
    <div id="map" style='width: 100%; height: 400px;'></div>
  </div>
  <div class="container contact-info-wrapper animation" data-animation="animated fadeInUp">
    <div class="col-md-12">
      <h3>Contact Details</h3>
    </div>
    <div class="col-lg-4 col-sm-12 float-left contact-details">
      <span><i class="fa fa-phone-square"></i>8888-8888</span>
      <span><i class="fa fa-envelope"></i><a href="mailto:info@caffora.cafe">info@telescopehr.com</a></span>
      <span><i class="fa fa-building"></i>Heredia, Costa Rica</span>
    </div>
    <div class="col-lg-8 col-sm-12 float-left contact-form-wrapper">
      <%= render :file => '/messages/new' %>
    </div>
  </div>
</div>

app/views/index/home.html.erb
<div class="home-slider-wrapper">
	<div id="home-slider" class="home-slider">
    <div class="slide">
      <%= image_tag 'pex7.jpg' %>
      <div class="home-slider-overlay home-slider-blue overlay-upper-blue"></div>
      <div class="home-slider-overlay home-slider-blue overlay-lower-blue"></div>
      <div class="home-slider-overlay home-slider-dark overlay-upper-dark"></div>
      <div class="home-slider-overlay home-slider-dark overlay-lower-dark"></div>
      <div class="home-slider-content">
        <h2 class="animated">We <strong>create</strong> what you need</h2>
      </div>
    </div>
    <div class="slide">
      <%= image_tag 'pex1.jpg' %>
      <div class="home-slider-overlay home-slider-blue overlay-upper-blue"></div>
      <div class="home-slider-overlay home-slider-blue overlay-lower-blue"></div>
      <div class="home-slider-overlay home-slider-dark overlay-upper-dark"></div>
      <div class="home-slider-overlay home-slider-dark overlay-lower-dark"></div>
      <div class="home-slider-content">
        <h2 class="animated">Let us <strong>improve</strong> your business</h2>
      </div>
    </div>
    <div class="slide">
      <%= image_tag 'pex9.jpg' %>
      <div class="home-slider-overlay home-slider-blue overlay-upper-blue"></div>
      <div class="home-slider-overlay home-slider-blue overlay-lower-blue"></div>
      <div class="home-slider-overlay home-slider-dark overlay-upper-dark"></div>
      <div class="home-slider-overlay home-slider-dark overlay-lower-dark"></div>
      <div class="home-slider-content">
        <h2 class="animated">Web resources to help you <strong>grow</strong></h2>
      </div>
    </div>
	</div>
</div>

<div class="hello-wrapper">
  <div class="container hello-container">
    <div class="col-lg-12">
      <div class="col-lg-6 col-sm-12 animation2" data-animation="animated fadeInLeft">
        <div class="hello-background-container">
          <div class="col-lg-12 hello-background">
            <h2 style="text-align: right;">Hello. We are Swoop
              <br>Creative &amp; Interactive Studio
              <br>Make creative projects
            </h2>
          </div>
        </div>
        <div class="hello-shadow-container">
          <div class="col-lg-12 hello-shadow"></div>
        </div>
      </div>
      <div class="col-lg-6 col-sm-12 hello-information">
        <div class="col-lg-12">
          <p>Typical ad agency clients include businesses and corporations,non-profit organizations and private agencies. Agencies may be hired to produce television and radio commercials.</p>
          <p>Online advertising, out-of-home advertising, mobile marketing, and AR advertising, as part of an advertising campaign.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="services-wrapper">
  <div class="container" >
    <div class="page-head animation2" data-animation="animated fadeInUp">
      <h6 class="">What we do</h6>
      <h1 class="">What We Do</h1>
    </div>
  </div>
  <div class="container">
    <div class="col-lg-4 animation2" data-animation="animated fadeInUp">
      <div class="service-card-container">
        <%= link_to services_path, class: 'link-service-card' do %>
          <div class="service-card">
            <span><i class="fas fa-pen-nib"></i></span>
            <h4>Creative Design</h4>
          </div>
        <% end %>
        <div class="figure figure-1"></div>
      </div>
    </div>
    <div class="col-lg-4 animation2" data-animation="animated fadeInUp">
      <div class="service-card-container">
        <%= link_to services_path, class: 'link-service-card' do %>
          <div class="service-card">
            <span><i class="fas fa-code"></i></span>
            <h4>Development</h4>
          </div>
        <% end %>
        <div class="figure figure-2"></div>
      </div>
    </div>
    <div class="col-lg-4 animation2" data-animation="animated fadeInUp">
      <div class="service-card-container">
        <%= link_to services_path, class: 'link-service-card' do %>
          <div class="service-card">
            <span><i class="fab fa-gg-circle"></i></span>
            <h4>Branding</h4>
          </div>
        <% end %>
        <div class="figure figure-3"></div>
      </div>  
    </div>
  </div>
</div>

<div class="projects-wrapper">
  <div class="col-lg-6 projects-information-wrapper animation2" data-animation="animated fadeInLeft">
    <div class="projects-information">
      <div class="page-head">
        <h6 class="">What we do</h6>
        <h1 class="">We’re Swoop Agency Creative & Interactive Studio</h1>
        <p>Use of creativity by agencies is “unexpected” because so much advertising today is expected. This will capture attention of audiences, therefore the message is likely to get through.</p>
      </div>
      <div class="graph-wrapper">
        <div class="graph">5</div>
        <span>Projects</span>
      </div>
    </div>
  </div>
  <div class="col-lg-6 animation2" data-animation="animated fadeInRight">
    <div class="projects-image-container">
      <div class="projects-image">
        <%= image_tag 'mac.png' %>
      </div>
      <div class="projects-link-shadow"></div>
      <div class="projects-link">
        <h4>Check Our Projects</h4>
        <%= link_to 'Portfolio', portfolio_path %>
      </div>
    </div>
  </div>
</div>

app/views/index/projects.html.erb
<div class="view-head">
  <h2 class="animation" data-animation="animated fadeInRight">Portfolio</h2>
</div>
<div class="portfolio-wrapper">
  <div class="container">
    <div class="page-head-right">
      <div class="head-info">
        <h1 class="animation" data-animation="animated fadeInLeft" >Our Projects</h1>
        <h6 class="animation" data-animation="animated fadeInLeft">Check Our Work</h6>
      </div>
    </div>
  </div>
  <div class="portfolio-gallery-wrapper animation" data-animation="animated fadeInUp">
    <%= link_to project_backyard_path do %>
      <div class="box portfolio-gallery col-lg-3 col-md-6">
        <div class="box-img">
          <%= image_tag 'post-15.jpg' %>
          <div class="portfolio-gallery-overlay">
            <div class="overlay-content">
              <h3>BackyardLinks</h3>
              <h2>Project Description</h2>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="box portfolio-gallery col-lg-3 col-md-6">
      <div class="box-img">
        <%= image_tag 'post-16.jpg' %>
        <div class="portfolio-gallery-overlay">
          <div class="overlay-content">
            <h3>BackyardLinks</h3>
            <h2>Project Description</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="box portfolio-gallery col-lg-3 col-md-6">
      <div class="box-img">
        <%= image_tag 'post-18.jpg' %>
        <div class="portfolio-gallery-overlay">
          <div class="overlay-content">
            <h3>BackyardLinks</h3>
            <h2>Project Description</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="box portfolio-gallery col-lg-3 col-md-6">
      <div class="box-img">
        <%= image_tag 'post-19.jpg' %>
        <div class="portfolio-gallery-overlay">
          <div class="overlay-content">
            <h3>BackyardLinks</h3>
            <h2>Project Description</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="box portfolio-gallery col-lg-3 col-md-6">
      <div class="box-img">
        <%= image_tag 'post-20.jpg' %>
        <div class="portfolio-gallery-overlay">
          <div class="overlay-content">
            <h3>BackyardLinks</h3>
            <h2>Project Description</h2>
          </div>
        </div>
      </div>
    </div>
      <div class="box portfolio-gallery col-lg-3 col-md-6">
      <div class="box-img">
        <%= image_tag 'post-15.jpg' %>
        <div class="portfolio-gallery-overlay">
          <div class="overlay-content">
            <h3>BackyardLinks</h3>
            <h2>Project Description</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="box portfolio-gallery col-lg-3 col-md-6">
      <div class="box-img">
        <%= image_tag 'post-16.jpg' %>
        <div class="portfolio-gallery-overlay">
          <div class="overlay-content">
            <h3>BackyardLinks</h3>
            <h2>Project Description</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="box portfolio-gallery col-lg-3 col-md-6">
      <div class="box-img">
        <%= image_tag 'post-18.jpg' %>
        <div class="portfolio-gallery-overlay">
          <div class="overlay-content">
            <h3>BackyardLinks</h3>
            <h2>Project Description</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="box portfolio-gallery col-lg-3 col-md-6">
      <div class="box-img">
        <%= image_tag 'post-19.jpg' %>
        <div class="portfolio-gallery-overlay">
          <div class="overlay-content">
            <h3>BackyardLinks</h3>
            <h2>Project Description</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="box portfolio-gallery col-lg-3 col-md-6">
      <div class="box-img">
        <%= image_tag 'post-20.jpg' %>
        <div class="portfolio-gallery-overlay">
          <div class="overlay-content">
            <h3>BackyardLinks</h3>
            <h2>Project Description</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="box portfolio-gallery col-lg-3 col-md-6">
      <div class="box-img">
        <%= image_tag 'post-19.jpg' %>
        <div class="portfolio-gallery-overlay">
          <div class="overlay-content">
            <h3>BackyardLinks</h3>
            <h2>Project Description</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="box portfolio-gallery col-lg-3 col-md-6">
      <div class="box-img">
        <%= image_tag 'post-20.jpg' %>
        <div class="portfolio-gallery-overlay">
          <div class="overlay-content">
            <h3>BackyardLinks</h3>
            <h2>Project Description</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="dark-wrapper">
    <div class="dark-information-wrapper col-lg-6">
      <div class="dark-information animation2" data-animation="animated fadeInLeft">
        <div class="page-head">
          <h6>WE MAKE IT</h6>
          <h1>Unlimited Creative</h1>
          <p>This was one trait that advertising agencies were perceived to not always have. It was suggested that on occasions that media planner and researchers.</p>
        </div>
      </div>
    </div>
    <div class="dark-window col-lg-6 animation2" data-animation="animated fadeInRight">
      <div class="dark-line">
        <div class="col-lg-6 col-md-6">
          <%= image_tag 'tree.jpg' %>
        </div>
        <div class="dark-content-wrapper col-lg-6 col-md-6 dark-right">
          <div class="dark-content">
            <span><i class="fab fa-fly"></i></span>
            <h3>We Make  Creative Projects</h3>
          </div>
        </div>
      </div>
      <div class="dark-line">
        <div class="dark-content-wrapper col-lg-6 col-md-6">
          <div class="dark-content">
            <span><i class="fas fa-user-astronaut"></i></span>
            <h3>We Make  Creative Projects</h3>
          </div>
        </div>
        <div class="col-lg-6 col-md-6 dark-right">
          <%= image_tag 'bulb.jpg' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/index/services.html.erb
<div class="view-head">
  <h2 class="animation" data-animation="animated fadeInRight">Services</h2>
</div>
<div class="services-page-wrapper">
  <div class="container">
    <div class="page-head-right">
      <div class="head-info">
        <h1 class="animation" data-animation="animated fadeInLeft">What We Do</h1>
        <h6 class="animation" data-animation="animated fadeInLeft">What we do</h6>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="col-lg-4 animation" data-animation="animated fadeInUp">
      <div class="service-card-container">
        <div class="service-card">
          <span><i class="fas fa-pen-nib"></i></span>
          <h4>Creative Design</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
        <div class="figure figure-1"></div>
      </div>
    </div>
    <div class="col-lg-4 animation" data-animation="animated fadeInUp">
      <div class="service-card-container">
        <div class="service-card">
          <span><i class="fas fa-code"></i></span>
          <h4>Development</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
        <div class="figure figure-2"></div>
      </div>
    </div>
    <div class="col-lg-4 animation" data-animation="animated fadeInUp">
      <div class="service-card-container">
        <div class="service-card">
          <span><i class="fab fa-gg-circle"></i></span>
          <h4>Branding</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
        <div class="figure figure-3"></div>
      </div>  
    </div>
  </div>
</div>
<div class="testimonial-wrapper">
  <%= image_tag 'pex3.jpg' %>
  <div class="testimonial-overlay"></div>
  <div class="testimonial-content animation2" data-animation="animated fadeInUp">
    <div class="container">
      <div class="page-head">
        <h1 class="">What Our Clients Say</h1>
      </div>
      <div id="testimonial-slider" class="testimonial-slider">
        <div class="slide">
          <p>“Incredible! What you did for our company was amazing. I recommend your services to all friends and colleagues”</p>
          <span><i class="fas fa-angle-double-down"></i></span>
          <h4>Juan Vega</h4>
        </div>
        <div class="slide">
          <p>“Incredible! What you did for our company was amazing. I recommend your services to all friends and colleagues”</p>
          <span><i class="fas fa-angle-double-down"></i></span>
          <h4>Juan Vega</h4>
        </div>
        <div class="slide">
          <p>“Incredible! What you did for our company was amazing. I recommend your services to all friends and colleagues”</p>
          <span><i class="fas fa-angle-double-down"></i></span>
          <h4>Juan Vega</h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="menu-wrapper">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= active_link_to 'Home', root_path, active: :exclusive, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= active_link_to 'Portfolio', portfolio_path, active: :inclusive, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= active_link_to 'Services', services_path, active: :exclusive, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= active_link_to 'About', about_path, active: :exclusive, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= active_link_to 'Contact', contact_path, active: :exclusive, class: 'nav-link' %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backyard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="turbolinks-cache-control" content="no-cache">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- <link href="https://fonts.googleapis.com/css?family=Philosopher:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Athiti:200,300,400,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merriweather:300,400,400i,700" rel="stylesheet">-->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,400i,500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    
    <script src="//maps.google.com/maps/api/js?key=AIzaSyCOxwVM7_4AGL480Epgg7L483h4ITGKmqg"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  </head>

  <body>
    <%= image_tag 'icon-logo.png', class: 'back-image' %>
    <div class="body-wrapper">
      <div class="main-wrapper"> 
        <header>
          <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
            <%= link_to root_path, class: 'navbar-brand' do %>
              <%= image_tag 'icon.png' %>
            <% end %>
            <div class="navbar-toggler">
              <i class="fa fa-bars" aria-hidden="true"></i>
            </div>

            <div class="collapse navbar-collapse" id="navbarColor01">
              <%= render 'layouts/nav' %>
            </div>
            </div>
            <div class="nav-mobile">
              <%= render 'layouts/nav' %>
            </div>
          </nav>

        </header>
        <% if !(params[:controller] == 'index' && params[:action] == 'home') %>
          <div class="header-background animation-wrapper">
            <%= image_tag 'pex1.jpg' %>
            <div class="header-overlay"></div>
          </div>
        <% end %>
        <%= yield %>
        <div id="render-alert">
            <%= bootstrap_flash %>
        </div>
        <footer>
          <div class="footer-wrapper container">
            <div class="col-lg-2 col-md-6">
              <%= render 'layouts/nav' %>
            </div>
            <div class="footer-contact-details col-lg-4 col-md-6">
              <ul>
                <li class="nav-item"><span class="nav-link"><i class="fa fa-phone-square"></i>8888-8888</span></li>
                <li class="nav-item"><span class="nav-link"><i class="fa fa-envelope"></i><a href="mailto:info@caffora.cafe">info@telescopehr.com</a></span></li>
                <li class="nav-item"><span class="nav-link"><i class="fa fa-building"></i>Heredia, Costa Rica</span></li>
              </ul>
            </div>
            <div class="col-lg-6">
              <%= link_to root_path, class: 'navbar-brand' do %>
                <%= image_tag 'icon.png' %>
              <% end %>
            </div>
          </div>
          <div class="copyright">
            <small>Created by BackyardLinks ©</small>
          </div>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/messages/_errors.html.erb
<% if @message.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:</h2>

    <ul>
    <% @message.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/messages/create.js.erb
<% if @message.errors.any? %>
	$('.message_errors').html("<%= j (render 'errors') %>");
<% else %>
	$(".form-clear").val('');
	$('#render-alert').html('<div class="alert fade in alert-success "><button type="button" class="close" data-dismiss="alert">×</button>Email was sent.</div>');
<% end %>

app/views/messages/new.html.erb
<%= form_for @message, url: contact_path, :html => { :class => "form-horizontal contact", remote: true } do |message_form| %>
  <div class="form-group">
    <div>
      <%= message_form.text_field :name, :class => 'form-contact form-clear', placeholder: 'Name', :required => true %>
    </div>
  </div>
  <div class="form-group">
    <div>
      <%= message_form.email_field :email, :class => 'form-contact form-clear', placeholder: 'Email', :required => true %>
    </div>
  </div>
  
  <div class="form-group">
    <div>
      <%= message_form.text_area :content, :class => 'form-contact form-clear', placeholder: 'Message', rows: 5, :required => true %>
    </div>
  </div>
  
  <div class="form-group">
    <div>
      <%= button_tag(type: "submit", class: "btn btn-primary btn-standard") do %>
        <%= t('.send') %>
      <% end %>
    </div>
  </div>
<% end %>
<div class="message_errors">
  
</div>